apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fio-nfs-test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: REPLACE_WITH_NFS_STORAGE_CLASS
  resources:
    requests:
      storage: 50Gi
